---
toc: true
format:
  html: default
  pdf: default
  arxiv-pdf:
    keep-tex: true


bibliography: bibliography.bib

title: The Name of the Title Is Hope

# if short-title is defined, then it's used
short-title: Hope

author:
  - name: Max Gabler
    email: max.gabler@uni-ulm.de
  - name: Wanshu Jiang
    email: wanshu.jiang@uni-ulm.de
  - name: Christoph Kiesl
    email: christoph.kiesl@uni-ulm.de
#    affiliation:
#      name: Institute for Clarity in Documentation
#      address: P.O. Box 1212
#      city: Dublin
#      state: Ohio
#      country: USA
#      postal-code: 43017-6221
  - name: Leonard Pöhls
    email: leonard.poehls@uni-ulm.de
  - name: Alexander Rieber
    email: alexander.rieber@uni-ulm.de
#    affiliation:
#      name: 
#      address: 
#      city:
#      state:
#      country:
  - name: Ansgar Scherp
    email: ansgar.scherp@uni-ulm.de
#    affiliation:
#      name:
#      address:
#      city:
#      state: 
#      country:

# acm-specific metadata
acm-metadata:
  # comment this out to make submission anonymous
  # anonymous: true

  # comment this out to build a draft version
  #final: true

  # comment this out to specify detailed document options
  # acmart-options: sigconf, review  

  # acm preamble information
  copyright-year: 2018
  acm-year: 2018
  copyright: acmcopyright
  doi: XXXXXXX.XXXXXXX
  conference-acronym: "Conference acronym 'XX"
  conference-name: |
    Make sure to enter the correct
    conference title from your rights confirmation emai
  conference-date: June 03--05, 2018
  conference-location: Woodstock, NY
  price: "15.00"
  isbn: 978-1-4503-XXXX-X/18/06

  # if present, replaces the list of authors in the page header.
  shortauthors: Trovato et al.

  # The code below is generated by the tool at http://dl.acm.org/ccs.cfm.
  # Please copy and paste the code instead of the example below.
  ccs: |
    \begin{CCSXML}
    <ccs2012>
     <concept>
      <concept_id>10010520.10010553.10010562</concept_id>
      <concept_desc>Computer systems organization~Embedded systems</concept_desc>
      <concept_significance>500</concept_significance>
     </concept>
     <concept>
      <concept_id>10010520.10010575.10010755</concept_id>
      <concept_desc>Computer systems organization~Redundancy</concept_desc>
      <concept_significance>300</concept_significance>
     </concept>
     <concept>
      <concept_id>10010520.10010553.10010554</concept_id>
      <concept_desc>Computer systems organization~Robotics</concept_desc>
      <concept_significance>100</concept_significance>
     </concept>
     <concept>
      <concept_id>10003033.10003083.10003095</concept_id>
      <concept_desc>Networks~Network reliability</concept_desc>
      <concept_significance>100</concept_significance>
     </concept>
    </ccs2012>
    \end{CCSXML}
    
    \ccsdesc[500]{Computer systems organization~Embedded systems}
    \ccsdesc[300]{Computer systems organization~Redundancy}
    \ccsdesc{Computer systems organization~Robotics}
    \ccsdesc[100]{Networks~Network reliability}

  keywords:
    - 10-K
    - Business Model Innovation
    - BERT
    - Gemini
  
  # if uncommented, this produces a teaser figure
  # 
  # teaser:
  #   image: sampleteaser
  #   caption: figure caption
  #   description: teaser description    

abstract: |
  A clear and well-documented \LaTeX\ document is presented as an
  article formatted for publication by ACM in a conference proceedings
  or journal publication. Based on the "acmart" document class, this
  article presents and explains many of the common variations, as well
  as many of the formatting elements an author may use in the
  preparation of the documentation of their work.

---

# Introduction

Business model innovation (BMI) is a key activity to maintain competitiveness and even gain a competitive advantage [@pucihar_drivers_2019; @teece_business_2018]. It is therefore no surprise that the interest in BMI and methods of measuring it has grown rapidly over the last twenty years. Researchers have recently called for a BMI measurement instrument that is more comprehensive and advanced than already existing ones [@huang_review_2023]. The scale developed by Spieth & Schneider [-@spieth_business_2016] provides managers and practitioners with a measurement index for business model innovativeness. This measurement model only validates applicability of BMI theory [@huang_review_2023] and is insufficient for longitudinal studies [@clauss_measuring_2017]. Hence, this measure is not adequate for a time series analysis of BMI. Furthermore, it refers only to BMI as new-to-the-firm and is not able to grasp BMI in the sense of new-to-the-industry and new-to-market.

-	Solution approach (both after we actually are final with approach and have (some) results)

-	Results

Our contribution is made in a number of ways. Firstly, we tackle two issues raised in the study by Lee & Hong [-@lee_business_2014]: we employ a more reliable and contemporary methodology for extracting the business model (BM) from 10-K filings and we are able to extend the scope of their study. Secondly, we build on the concept of alternative industry classification put forth by Hoberg & Phillips [-@hoberg_text-based_2016] and propose an industry classification system based on a firm's BM. Thirdly, we propose a novel measure for BMI that is sufficient for longitudinal studies.

# Related Work

Our study borders several research fields and thus we have a variaty of literature to cover. Section 2.1 presents state of the art measures of BMI while Section 2.2 examines the relationship between BMI and the financial performance of a firm. Section 2.3 deals with previous approaches to text mine 10-K filings. Finally, in Section 2.4 a summary of the findings from the related work is presented. 

## Measuring Business Model Innovation

In spite of the growing interest in BMI and the increasing number of theoretical and empirical studies in this field, the research of BMI is still in a preliminary state [@huang_review_2023]. Consequently, there is considerable variation in the definitions of BMI, with some definitions being more similar to one another than others [@foss_fifteen_2017]. Spieth & Schneider [-@spieth_business_2016] identify three core dimensions a company’s BM is comprised of: its value proposition, its value creation architecture and its revenue model logic. Based on this, BMI can be conceptualized as a change that is new-to-the-firm in at least one of these dimensions. Furthermore, Spieth and Schneider [-@spieth_business_2016] introduce a measurement model to evaluate these three dimensions of BMI. They develop an index by first specifying the contents, followed by a specification of the indicators and assessing their content validity, assessing the indicators collinearity and finally assessing the external validity. A total of twelve indicators for measuring the innovativeness of the BM were identified through a comprehensive literature review and through engagement with industry practitioners. The external validity of the formative indicators was successfully validated through a survey of 200 experts in strategy and innovation management [@spieth_business_2016]. Clauss [-@clauss_measuring_2017] employs a very similar approach. After specifying the domain and dimensionality of BMI trough literature research, the author divides his scale into three hierarchical levels consisting of 41 reflective items, 10 subconstructs and three main dimensions, which are similar to the ones mentioned earlier. The scale was validated through two samples from the manufacturing industry and further demonstrated nomological validity [@clauss_measuring_2017]. However, both measures are subject to three significant limitations. Firstly, both measures lack a temporal component. Consequently, they are inadequate for use in longitudinal studies or ex-post evaluations of BMI. Secondly, BMI is only measured at the new-to-the-firm level rather than at the new-to-the-industry or new-to-the-market level. Thirdly, both measures rely on interviews and questionnaires, which makes conducting large-scale studies time-consuming and reliant on the willingness of the companies to cooperate [@clauss_measuring_2017;@spieth_business_2016].

## BMI and Firm Performance

A number of studies have examined the relationship between BMI and the financial performance of a company. These studies differ in terms of sample size and characteristics, methodology and choice of measures [@foss_fifteen_2017;@white_exploring_2022]. Cucculelli & Bettinelli [-@cucculelli_business_2015] for example investigate the effect of BMI on sales growth, return on sales (ROS) and total factor productivity (TFP) in a sample of 376 Italian SMEs in the years 2000-2010. The results provide support for the hypothesis that BMI has a positive effect on firm performance, with the effect increasing in line with the intensity of the innovation. Latifi et al. [-@latifi_business_2021] use a cross-industry sample of 563 European SMEs and provide support for the hypothesis that a company engaging in BMI will improve its overall firm performance. In their study, the firm performance is evaluated subjectively in accordance with the model proposed by Venkatraman & Ramanujam [-@venkatraman_measurement_1986]. White et al. [-@white_exploring_2022] conducted a meta-analysis based on the extant BMI literature. After an extensive search of the literature, they identified 77 studies comprising 26,050 firms from 26 countries and six continents. They found a positive relationship between BMI and firm performance, and that this relationship is shaped by factors including the firm age, industry, the economic and political environment and BMI characteristics.

## Text Mining 10-K Filings

The process of text mining 10-K filings is not a novel concept. Hoberg & Phillips [-@hoberg_text-based_2016] present a novel approach to defining industry boundaries. This is achieved through the parsing of the product descriptions provided by firm 10-K filings and creating word vectors. Specifically, the authors identify and exclude proper nouns, which include common words and geographic locations.They then create word vectors for each firm and year, which enables the measurement of product similarity over time. In this way the authors demonstrate shortcomings in the traditional industry classification systems such as the Standard Industry Classification (SIC) and the North American Industry Classification System (NAICS), which are not able to account for temporal changes. The new method is capable of capturing changes in industry boundaries and competitor sets over time, thereby providing a dynamic industry classification system. Furthermore, the authors' findings indicate a correlation between firms’ R&D and advertising expenditures and an increase in product differentiation. This underscores the significance of product differentiation. In their study, Lee & Hong [-@lee_business_2014] examine the evolution of a firm's BM over time. The authors thus utilize the procedure proposed by Miner et al. [-@miner_practical_2012] to represent each document as a vector of keywords, which is similar to the approach utilized by Hoberg & Phillips [-@hoberg_text-based_2016]. After identifying the Item 1 part of the 10-K filings as the most crucial part for describing a firm's BM, Lee & Hong [-@lee_business_2014] filter these for relevant sentences. Subsequently, the authors construct  keyword vectors, which represent the concept of the BM. Therefore, the evolution of the BM is depicted as the change in the distribution of keywords over time. Nevertheless, this approach is not without shortcomings. The authors advocate for a more robust methodology, such as incorporating multi-word phrases in the keyword vectors, to enhance the reliability of the approach [@lee_business_2014].

## Summary

BMI is a complex concepts with different definitions and dimensions which makes it hard to measure. Existing scale-measures fulfill their purpose but are not sufficient to be used in large-scale, longitudinal studies. Furthermore, researchers have to rely on interviews and questionnaires, thus making them reliant on the willingness of firms to cooperate. Despite these difficulties, researchers still found ways to measure a positive relationship between BMI and a firms performance. This relationship is shaped not only by the choice of measurement of BMI and firm performance but also by factors like firm age, industry, and economic and political environment. 

# Methods

## Assumptions

## Gemini

- Repo Workflow

- Prompt Info

- Descriptive Table1 for document length of original filings for why we use Gemini

## BERT

## BERTScore

## Hierarchical Agglomerative Clustering

# Experimental Apparatus

## Datasets

We collect 10-Ks filings from the digital SEC Database, using the category “10-K” as extraction condition. Since the focus of our study lies on company's BM, we only use the Item 1 part, since this is the most crucial part of the 10-K filings for describing the companys BM [@lee_business_2014]. 

//Our observations are limited to an intersection of such companies, which on the one hand has been made available to the SEC since 2001 in a publicly accessible list of 10.284 companies (Appendix), of which 7590 are listed (on stock exchange). On the other hand, we consider companies that filed 10-K reports with the SEC between 2017 and 2023 //-> rewrite as step by step, how we got to the final list of companys

We exclude companies from the financial sector, namely companies with a SIC Code starting with six. We consider the filings from 2017 to 2023. 


TODO

- Table2 like Alex suggested

- Descriptive Table3 for document length of processed filings
- Description of Table3 and the final Dataset

## Pre-Processing

- everything regarding Gemini in Pre-Processing

Since the parts of section I are generally not well structured for further processing, we use Gemini to summarize the texts with emphasis on the business description. Based on this data, we create similarity scores between different companies and the same companies from different years. Finally, we match these firms with several financial numbers that we extracted from Eikon/Datastream. 

## Procedure

Before generating the final datasets, we had to iteratively coordinate various steps over several phases in order to generate the data consistently. The first step was to extract the required company identifiers (CIKs) from the SEC database.

# Results

# Discussion

# Conclusion

# Limitations

# Acknowledgement

- Jonathan for IT Support
- Prof. Kranz for Repo

